name: Deploy AI-CRM Infra + Function

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v3

      - name: Login en Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy infraestructura con Bicep
        run: |
          az deployment sub create \
            --location uksouth \
            --template-file infra/main.bicep \
            --parameters functionAppName=func-ai-crm2 \
                        storageAccountName=stcrm1753223711 \
                        keyVaultName=kv-ai-crm

      - name: Publicar código Function App
        uses: azure/webapps-deploy@v2
        with:
          app-name: func-ai-crm2
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_FUNC_AI_CRM2 }}
          package: .
