name: Deploy AI-CRM Infra + Function

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v3

      - name: Login en Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Crear resource group si no existe
        run: |
          az group create --name rg-ai-crm --location eastus

      - name: Deploy infraestructura con Bicep
        run: |
          az deployment group create \
            --resource-group rg-ai-crm \
            --template-file infra/main.bicep \
            --parameters functionAppName=funcaicrmv2 \
                        storageAccountName=stcrmaicrmv2001 \
                        hostingPlanName=plan-ai-crm-linux


      - name: Deploy código de Function App
        uses: azure/webapps-deploy@v2
        with:
          app-name: funcaicrmv2          # ← debe coincidir con el nombre del Bicep
          slot-name: production
          package: .

