name: Deploy AI-CRM Infra + Function

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v3

      - name: Login en Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Crear resource group si no existe
        run: |
          az group create --name rg-ai-crm --location eastus

      - name: Deploy infraestructura con Bicep
        run: |
          az deployment group create \
          --resource-group rg-ai-crm \
          --template-file infra/main.bicep \
          --parameters functionAppName=funcaicrmclean \
                      storageAccountName=stcrmaicrmclean01 \
                      keyVaultName=kvaicrmclean
        
